/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import conexao.conexao;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrador
 */
public class emprestimo extends javax.swing.JFrame {
    Connection con;
    Statement stm;
    ResultSet rs;
    Date d = new Date();
    /**
     * Creates new form emprestimo
     */
    public emprestimo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Emprestimo");
        setAlwaysOnTop(true);
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setFocusCycleRoot(true);

        jLabel1.setText("Armário:");

        jLabel2.setText("Tipo:");

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel3.setText("Situação:");

        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });

        jLabel4.setText("Emprestimo:");

        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });

        jLabel5.setText("Crachá:");

        jLabel6.setText("Nome:");

        jLabel7.setText("Setor:");

        jLabel8.setText("Função:");

        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jTextField5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField5KeyTyped(evt);
            }
        });

        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });

        jButton1.setText("Emprestar");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Remover");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3)
                            .addComponent(jLabel8, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTextField8)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(34, 34, 34)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        this.setLocationRelativeTo(null);
        this.requestFocus();
        jTextField1.setEditable(false);
        jTextField2.setEditable(false);
        jTextField3.setEditable(false);
        jTextField4.setEditable(false);
        jTextField6.setEditable(false);
        jTextField7.setEditable(false);
        jTextField8.setEditable(false);
        jTextField1.setFocusable(false);
        jTextField2.setFocusable(false);
        jTextField3.setFocusable(false);
        jTextField4.setFocusable(false);
        jTextField6.setFocusable(false);
        jTextField7.setFocusable(false);
        jTextField8.setFocusable(false);
        jTextField5.requestFocus();
        int paramentroBuscaCol = 0;
        try{
        principal p = new principal();
        con = conexao.conectar();
        String sql = "SELECT id,tipo,situacao,date_format(dataemp,'%d/%m/%Y'),colaborador FROM armario WHERE ID="+String.valueOf(p.ob)+"";
        stm = con.createStatement();
        rs = stm.executeQuery(sql);
        while(rs.next()){
            if(rs.getString(2).equals("MASCULINO")){
                jTextField1.setText(String.valueOf(rs.getInt(1)));
            }else{
                jTextField1.setText(String.valueOf(rs.getInt(1)-2000));
                System.out.println("oi");
            }
            System.out.println(String.valueOf(p.ob));
            System.out.println(rs.getInt(1));
            jTextField2.setText(rs.getString(2));
            System.out.println(rs.getString(2));
            if(rs.getInt(3) == 0){
                jTextField3.setText("DISPONÍVEL");
                jButton3.setEnabled(false);
            }else{
                jTextField3.setText("OCUPADO");
                jButton1.setEnabled(false);
            }
            System.out.println();
            jTextField4.setText(String.valueOf(rs.getObject(4)));
            if(jTextField4.getText().equals("null")){
                jTextField4.setText("");
            }
            if(rs.getInt(5) != 0){
                jTextField5.setText(String.valueOf(rs.getInt(5)));
                paramentroBuscaCol = rs.getInt(5);
            }
        }
        sql = "SELECT * FROM colaborador WHERE cracha="+paramentroBuscaCol+"";
        stm = con.createStatement();
        rs = stm.executeQuery(sql);
        while(rs.next()){
            jTextField6.setText(rs.getString("nome"));
            jTextField7.setText(rs.getString("setor"));
            jTextField8.setText(rs.getString("funcao"));
            jTextField5.setEditable(false);
            jTextField5.setFocusable(false);
            jButton1.setEnabled(false);
            jButton3.setEnabled(true);
        }
        }catch(SQLException e){
            System.out.println("Erro: "+e.getMessage());
        }
    }//GEN-LAST:event_formWindowOpened

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int op;
        op = JOptionPane.showConfirmDialog(rootPane, "Deseja realmente cancelar?", "Confirmação", JOptionPane.OK_CANCEL_OPTION);
        if(op == 0){
            this.dispose();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyTyped
        
    }//GEN-LAST:event_jTextField5KeyTyped

    private void jTextField5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField5KeyReleased
        int op = Integer.parseInt(jTextField5.getText());
        try{
            String sql = "SELECT * FROM colaborador WHERE cracha="+op+"";
            stm = con.createStatement();
            rs = stm.executeQuery(sql);
            while(rs.next()){
                jTextField6.setText(rs.getString("nome"));
                jTextField7.setText(rs.getString("setor"));
                jTextField8.setText(rs.getString("funcao"));
            }
        }catch(SQLException e){
            System.out.println("Erro:"+e.getMessage());
        }
    }//GEN-LAST:event_jTextField5KeyReleased

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        int check = 5;
        if (jTextField5.getText().equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Informe o colaborador");
            jTextField5.requestFocus();
            check = 0;
        }else
            if ((!jTextField5.getText().equals("")) && (jTextField6.getText().equals(""))) {
                JOptionPane.showMessageDialog(rootPane, "Colaborador não encontrado, se desejar realize o cadastro.\n"
                        + "Através da tabela colaborador > ícone novo colaborador");
                jTextField5.requestFocus();
                check = 0;
            }else{
                if (!jTextField4.getText().equals("")) {
                JOptionPane.showMessageDialog(rootPane, "Armário indisponível, remova o atual colaborador");
                check = 0;
                }
            }
        
        if(check == 5){
            int op;
            op = JOptionPane.showConfirmDialog(rootPane, "Confirma emprestimo?", "Confirmação", JOptionPane.OK_CANCEL_OPTION);
            if(op == 0){ 
                try {
                    String sql = "SELECT * FROM COLABORADOR WHERE CRACHA = "+jTextField5.getText();
                    con = conexao.conectar();
                    stm = con.createStatement();
                    rs = stm.executeQuery(sql);
                    while(rs.next()){
                        if(rs.getInt("armario") == 0){
                        if(rs.getString("sexo").equals(jTextField2.getText())){
                        if(jTextField2.getText().trim().equals("MASCULINO")){
                            sql = "UPDATE armario SET situacao = 1,colaborador="+jTextField5.getText()+",dataemp=(select curdate()) WHERE id="+jTextField1.getText()+"";
                        }else{
                            int armario = Integer.parseInt(jTextField1.getText()) + 2000;
                            System.out.println(armario+" oi teste aq");
                            sql = "UPDATE armario SET situacao = 1,colaborador="+jTextField5.getText()+",dataemp=(select curdate()) WHERE id="+armario;
                        }
                        con = conexao.conectar();
                        stm = con.createStatement();
                        stm.executeUpdate(sql);
                        if(jTextField2.getText().equals("MASCULINO")){
                            sql = "UPDATE colaborador SET armario ="+jTextField1.getText()+" WHERE cracha ="+jTextField5.getText();
                        }else{
                            int armario = Integer.parseInt(jTextField1.getText()) + 2000;
                            sql = "UPDATE colaborador SET armario ="+armario+" WHERE cracha ="+jTextField5.getText();
                        }
                        stm = con.createStatement();
                        stm.executeUpdate(sql);
                        JOptionPane.showMessageDialog(rootPane, "Armário emprestado com sucesso!");
                        this.dispose();
                        principal p = new principal();
                        p.atualizarTable();
                        con.close(); 
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Armário incompatível com o sexo do colaborador!","Erro",JOptionPane.ERROR_MESSAGE);
                            jTextField5.setText("");
                            jTextField6.setText("");
                            jTextField7.setText("");
                            jTextField8.setText("");
                            jTextField5.requestFocus();
                        }
                        }else{
                            JOptionPane.showMessageDialog(rootPane, "Colaborador ja possui armario!","Erro",JOptionPane.ERROR_MESSAGE);
                            jTextField5.setText("");
                            jTextField6.setText("");
                            jTextField7.setText("");
                            jTextField8.setText("");
                            jTextField5.requestFocus();
                        }
                    }
                    principal p = new principal();
                    p.atualizarTable();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(rootPane, "Erro: "+e.getMessage());
                }
                
            }
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try {
            int op;
            op = JOptionPane.showConfirmDialog(rootPane, "Confirma a remoção?", "Confirmação",2, JOptionPane.OK_CANCEL_OPTION);
            if(op == 0){
                String sql;
                if(jTextField2.getText().equals("MASCULINO")){
                    sql = "UPDATE armario SET SITUACAO=0,DATAEMP=NULL,COLABORADOR=NULL WHERE ID = "+jTextField1.getText();
                }else{
                    int armario = Integer.parseInt(jTextField1.getText()) + 1000;
                    System.out.println("oi");
                    System.out.println(armario);
                    sql = "UPDATE armario SET SITUACAO=0,DATAEMP=NULL,COLABORADOR=NULL WHERE ID = "+armario;
                }
                con = conexao.conectar();
                stm = con.createStatement();
                stm.executeUpdate(sql);
                sql = "UPDATE COLABORADOR SET ARMARIO=0 WHERE CRACHA = "+jTextField5.getText();
                con = conexao.conectar();
                stm = con.createStatement();
                stm.executeUpdate(sql);
                JOptionPane.showMessageDialog(rootPane, "Remoção realizado com sucesso!");
                this.dispose();
                principal p = new principal();
                p.atualizarTable();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null,"Ocorreu um erro durante o processo: "+e.getMessage(),"Erro durante a remoção", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        principal p = new principal();
        p.liberarTabela();
    }//GEN-LAST:event_formWindowClosed

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(emprestimo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new emprestimo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables
}
